# Generated by Django 4.1.5 on 2023-01-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='precount',
            new_name='precaution',
        ),
    ]
